# This file:
# ~/.scss-lint.yml
#
# Default file:
# /Library/Ruby/Gems/2.0.0/gems/scss_lint-X.XX.X/config/default.yml
#
# Initial installation instructions at repo:
# https://github.com/attenzione/SublimeLinter-scss-lint

linters:

  Comment:
    exclude: '**/*.css'

  EmptyLineBetweenBlocks:
    enabled: false

  LeadingZero:
    enabled: true
    style: include_zero

  MergeableSelector:
    force_nesting: false
